version: 2

updates:

  - package-ecosystem: "docker"
    directory: "/.github/container/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"