version: '3.7'

volumes:
  main_conf:
    name: main_conf
  main_logs:
    name: main_logs
  main_data:
    name: main_data
  main_uplo:
    name: main_uplo

services:

  main:
    container_name: ejabberd
    image: badlop/ejtestecs:latest
    environment:
      - ERLANG_NODE_ARG=ejabberd@main
      - ERLANG_COOKIE=dummycookie123
      - CTL_ON_CREATE=register admin localhost asd
      - CTL_ON_START=stats registeredusers ;
                     status
    command: ["foreground"]
    ports:
      #- "4369-4399:4369-4399"
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
      - "5443:5443"
    volumes:
      - main_conf:/opt/ejabberd/conf
      - main_data:/opt/ejabberd/database
      - main_logs:/opt/ejabberd/logs
      - main_uplo:/opt/ejabberd/upload
        #- ../ejabberd.yml.example:/opt/ejabberd/conf/ejabberd.yml:ro
